# Remember to also update the GitHub Actions configuration, as appropriate:
#   cc-legal-tools-app/.github/workflows/pre-commit.yml
#
# Also see:
#   .env
#   Dockerfile
#
# Use docker compose v2 for non swarm deployments
# https://docs.docker.com/compose/compose-file/compose-file-v2/

version: '2.4'

services:

  app:
    build: .
    command: ./manage.py runserver 0.0.0.0:${PORT_APP}
    environment:
      - DJANGO_SETTINGS_MODULE=${DOCKER_DJANGO_SETTINGS_MODULE}
    ports:
      - "127.0.0.1:${PORT_APP}:${PORT_APP}"
    restart: always
    volumes:
      - .:/home/cc/cc-legal-tools-app
      - ${RELPATH_DATA}:/home/cc/cc-legal-tools-data
